{
 "title": "Power Monitor / Node",
 "description": "Power Monitor / Node",
 "tags": [ "power-monitor-mixin" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(kepler_node_package_joules_total{container=\"power-monitor\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Node Package Power Consumption (W)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "W" }
   ],
   "targets": [
    {
     "expr": "kepler_node_package_watts{container=~\"power-monitor\", instance=~\"$instance\"}",
     "legendFormat": "(Package) - {{instance}}"
    }
   ]
  },
  {
   "title": "Node Core Power Consumption (W)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "W" }
   ],
   "targets": [
    {
     "expr": "kepler_node_core_watts{container=~\"power-monitor\", instance=~\"$instance\"}",
     "legendFormat": "(Core) - {{instance}}"
    }
   ]
  },
  {
   "title": "Node Dram Power Consumption (W)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "W" }
   ],
   "targets": [
    {
     "expr": "kepler_node_dram_watts{container=~\"power-monitor\", instance=~\"$instance\"}",
     "legendFormat": "(Dram) - {{instance}}"
    }
   ]
  },
  {
   "title": "Node Uncore Power Consumption (W)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "W" }
   ],
   "targets": [
    {
     "expr": "kepler_node_uncore_watts{container=~\"power-monitor\", instance=~\"$instance\"}",
     "legendFormat": "(Uncore) - {{instance}}"
    }
   ]
  }
 ]
}