{
 "title": "Current Stats",
 "panels": [
  {
   "title": "Current Node Power Consumption By Zone",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (zone) (kepler_node_cpu_watts{container=~\"power-monitor\", instance=~\"$node\", zone=~\"$zone\"})"
    }
   ]
  },
  {
   "title": "Current Node Active Power Consumption By Zone",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (zone) (kepler_node_cpu_active_watts{container=~\"power-monitor\", instance=~\"$node\", zone=~\"$zone\"})"
    }
   ]
  },
  {
   "title": "Current Node Idle Power Consumption By Zone",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (zone) (kepler_node_cpu_idle_watts{container=~\"power-monitor\", instance=~\"$node\", zone=~\"$zone\"})"
    }
   ]
  }
 ]
}
{
 "title": "Node Usage",
 "panels": [
  {
   "title": "Total Power Consumption (W) per Zone",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "W" }
   ],
   "targets": [
    {
     "expr": "sum by (zone) (kepler_node_cpu_watts{container=~\"power-monitor\", zone=~\"$zone\"})",
     "legendFormat": "Zone - {{zone}}"
    }
   ]
  },
  {
   "title": "Node Power Consumption (W) By Zone",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "kepler_node_cpu_watts{container=~\"power-monitor\", instance=~\"$node\", zone=~\"$zone\"}",
     "legendFormat": "{{zone}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Node Active Power Consumption (W) By Zone",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "kepler_node_cpu_active_watts{container=~\"power-monitor\", instance=~\"$node\", zone=~\"$zone\"}",
     "legendFormat": "{{zone}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Node Idle Power Consumption (W) By Zone",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "kepler_node_cpu_idle_watts{container=~\"power-monitor\", instance=~\"$node\", zone=~\"$zone\"}",
     "legendFormat": "{{zone}} - {{instance}}"
    }
   ]
  }
 ]
}