{
 "title": "Current Stats",
 "panels": [
  {
   "title": "Top 10 Power Consuming Namespaces (W) per Zone",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(10,sum by (pod_namespace,zone)(kepler_pod_cpu_watts{job=\"power-monitor\", zone=~\"$zone\"}))"
    }
   ]
  }
 ]
}
{
 "title": "Namespace Usage",
 "panels": [
  {
   "title": "Total Power Consumption of Pods in Namespace (W) per Zone",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "W" }
   ],
   "targets": [
    {
     "expr": "sum by (zone) (kepler_pod_cpu_watts{job=\"power-monitor\", pod_namespace=~\"$namespace\", zone=~\"$zone\"})",
     "legendFormat": "Zone - {{zone}}"
    }
   ]
  },
  {
   "title": "Pod Power Consumption (W) By Zone",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "W" }
   ],
   "targets": [
    {
     "expr": "kepler_pod_cpu_watts{job=\"power-monitor\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\", zone=~\"$zone\"}",
     "legendFormat": "{{zone}} - {{pod_name}}"
    }
   ]
  }
 ]
}