{
 "title": "Power Monitor / Info",
 "description": "Power Monitor Info",
 "tags": [ "power-monitor-mixin" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Node - Kepler Build Info",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max(kepler_build_info{container=~\"power-monitor\"}) by (arch, goversion, revision, version)"
    }
   ]
  },
  {
   "title": "Node - Kepler CPU Info",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "count(kepler_node_cpu_info{container=~\"power-monitor\"}) by (instance, model_name, vendor_id)"
    }
   ]
  },
  {
   "title": "Total Power Consumption (W) per Zone",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "W" }
   ],
   "targets": [
    {
     "expr": "sum by (zone_type) (label_replace({__name__=~\"kepler_node_.+_watts\", instance=~\".+\"}, \"zone_type\",\"$1\",\"__name__\", \"kepler_node_(.+)_watts\"))",
     "legendFormat": "Total {{zone_type}} Watts"
    }
   ]
  }
 ]
}