# NOTE: prometheus itself requires these rbac for service discovery
# ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/rbac.md#prometheus-rbac

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-discovery
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/metrics
      - services
      - endpoints
      - pods
      - configmaps
      - secrets
    verbs: [get, list, watch]
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs: [get, list, watch]
  - nonResourceURLs: [/metrics]
    verbs: [get]
