resources:
- ../../base

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: controller
      namespace: system
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/0
        value: --openshift
      - op: add
        path: /spec/template/spec/containers/0/args/1
        value: --deployment-namespace=power-monitor
      - op: add
        path: /spec/template/spec/containers/0/args/2
        value: --exp.reconciler.token.refresh-interval=24h
      - op: add
        path: /spec/template/spec/containers/0/args/3
        value: --exp.uwm.token.ttl=168h
