# Leader Election Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kepler-operator.fullname" . }}-leader-election
  namespace: {{ include "kepler-operator.namespace" . }}
  labels:
    {{- include "kepler-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
# Manager ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kepler-operator.fullname" . }}-manager
  labels:
    {{- include "kepler-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - namespaces
      - persistentvolumeclaims
      - serviceaccounts
      - services
    verbs:
      - create
      - delete
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes/metrics
      - nodes/proxy
      - nodes/stats
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts/token
    verbs:
      - create
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
    verbs:
      - create
      - delete
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - kepler.system.sustainable.computing.io
      - rbac.authorization.k8s.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheusrules
      - servicemonitors
    verbs:
      - create
      - delete
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - create
      - delete
      - list
      - patch
      - update
      - use
      - watch
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
# Metrics Auth ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kepler-operator.fullname" . }}-metrics-auth
  labels:
    {{- include "kepler-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
# Metrics Reader ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kepler-operator.fullname" . }}-metrics-reader
  labels:
    {{- include "kepler-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
# Leader Election RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kepler-operator.fullname" . }}-leader-election
  namespace: {{ include "kepler-operator.namespace" . }}
  labels:
    {{- include "kepler-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kepler-operator.fullname" . }}-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "kepler-operator.serviceAccountName" . }}
    namespace: {{ include "kepler-operator.namespace" . }}
---
# Manager ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kepler-operator.fullname" . }}-manager
  labels:
    {{- include "kepler-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kepler-operator.fullname" . }}-manager
subjects:
  - kind: ServiceAccount
    name: {{ include "kepler-operator.serviceAccountName" . }}
    namespace: {{ include "kepler-operator.namespace" . }}
---
# Metrics Auth ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kepler-operator.fullname" . }}-metrics-auth
  labels:
    {{- include "kepler-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kepler-operator.fullname" . }}-metrics-auth
subjects:
  - kind: ServiceAccount
    name: {{ include "kepler-operator.serviceAccountName" . }}
    namespace: {{ include "kepler-operator.namespace" . }}
