# Metrics Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kepler-operator.fullname" . }}-metrics-service
  namespace: {{ include "kepler-operator.namespace" . }}
  labels:
    {{- include "kepler-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    {{- include "kepler-operator.managerLabels" . | nindent 4 }}
    app.kubernetes.io/part-of: kepler-operator
---
# Webhook Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kepler-operator.fullname" . }}-webhook-service
  namespace: {{ include "kepler-operator.namespace" . }}
  labels:
    {{- include "kepler-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    {{- include "kepler-operator.managerLabels" . | nindent 4 }}
    app.kubernetes.io/part-of: kepler-operator
