#!/usr/bin/env bash

# copyright 2023.
#
# licensed under the apache license, version 2.0 (the "license");
# you may not use this file except in compliance with the license.
# you may obtain a copy of the license at
#
#     http://www.apache.org/licenses/license-2.0
#
# unless required by applicable law or agreed to in writing, software
# distributed under the license is distributed on an "as is" basis,
# without warranties or conditions of any kind, either express or implied.
# see the license for the specific language governing permissions and
# limitations under the license.
#

set -eu -o pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source "${SCRIPT_DIR}/common"

BASE_COLLECTION_PATH=$1

KEPLER_OPERATOR_LABELS="operators.coreos.com/kepler-operator.openshift-operators"
POWER_MONITORING_OPERATOR_LABELS="operators.coreos.com/power-monitoring-operator.openshift-operators"

get_olm() {
	oc get -n openshift-operators csv | grep kepler-operator && {
		log "collecting olm info for kepler-operator"
		run oc -n openshift-operators get olm -l "${KEPLER_OPERATOR_LABELS}"= \
			-oyaml "$OLM_INFO_DIR/kepler-operator-olm-resources.yaml"
	}

	oc get -n openshift-operators csv | grep power-monitoring-operator && {
		log "collecting olm info for power-monitoring-operator"
		run oc -n openshift-operators get olm -l "${POWER_MONITORING_OPERATOR_LABELS}"= \
			-oyaml "$OLM_INFO_DIR/power-mon-olm-resources.yaml"
	}

	return 0
}

get_summary() {
	log "collecting olm summary"
	run oc -n openshift-operators get olm -owide "$OLM_INFO_DIR/summary.txt"
}

main() {

	OLM_INFO_DIR=$BASE_COLLECTION_PATH/olm-info
	mkdir -p "$OLM_INFO_DIR"

	get_olm
	get_summary
}

main "$@"
