#!/usr/bin/env bash

get_timestamp() {
	date -u +"%Y-%m-%d %H:%M:%SZ"
}

log_file() {
	echo "$(get_timestamp) $*" >>"$LOGFILE_PATH"
}

log_stdout_and_file() {
	echo "$(get_timestamp) $*" | tee -a "$LOGFILE_PATH"
}

log() {
	log_stdout_and_file "$@"
}

run() {
	length=$(($# - 1))
	cmd=${*:1:$length}
	gather_file="${*: -1}"

	log_file "$cmd"
	$cmd >>"$gather_file" 2>>"$LOGFILE_PATH" || true
}
