#!/usr/bin/env bash

get_timestamp() {
	date -u +"%Y-%m-%d %H:%M:%SZ"
}

log_file() {
	echo "$(get_timestamp) $*" >>"$LOGFILE_PATH"
}

log_stdout_and_file() {
	echo "$(get_timestamp) $*" | tee -a "$LOGFILE_PATH"
}

log() {
	log_stdout_and_file "$@"
}

run() {
	local gather_file="${!#}"
	local cmd_args=("${@:1:$#-1}")

	log_file "${cmd_args[@]}"
	"${cmd_args[@]}" >>"$gather_file" 2>>"$LOGFILE_PATH" || true
}
