---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kepler-system-sustainable-computing-io-v1alpha1-powermonitor
  failurePolicy: Fail
  name: mpowermonitor.kb.io
  rules:
  - apiGroups:
    - kepler.system.sustainable.computing.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - powermonitors
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kepler-system-sustainable-computing-io-v1alpha1-powermonitor
  failurePolicy: Fail
  name: vpowermonitor.kb.io
  rules:
  - apiGroups:
    - kepler.system.sustainable.computing.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - powermonitors
  sideEffects: None
