name: Upload Coverage to Codecov
description: runs tests and upload the coverage to codecov
inputs:
  codecov_token:
    description: codecov token
    required: true
runs:
  using: composite
  steps:
    - name: Run tests and generate coverage
      shell: bash
      run: make test

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5.4.0
      with:
        fail_ci_if_error: true
        files: ./cov.out
        token: ${{ inputs.codecov_token }}
