//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Kepler Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapRef) DeepCopyInto(out *ConfigMapRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapRef.
func (in *ConfigMapRef) DeepCopy() *ConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(ConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerMonitor) DeepCopyInto(out *PowerMonitor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerMonitor.
func (in *PowerMonitor) DeepCopy() *PowerMonitor {
	if in == nil {
		return nil
	}
	out := new(PowerMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PowerMonitor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerMonitorInternal) DeepCopyInto(out *PowerMonitorInternal) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerMonitorInternal.
func (in *PowerMonitorInternal) DeepCopy() *PowerMonitorInternal {
	if in == nil {
		return nil
	}
	out := new(PowerMonitorInternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PowerMonitorInternal) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerMonitorInternalDashboardSpec) DeepCopyInto(out *PowerMonitorInternalDashboardSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerMonitorInternalDashboardSpec.
func (in *PowerMonitorInternalDashboardSpec) DeepCopy() *PowerMonitorInternalDashboardSpec {
	if in == nil {
		return nil
	}
	out := new(PowerMonitorInternalDashboardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerMonitorInternalKeplerConfigSpec) DeepCopyInto(out *PowerMonitorInternalKeplerConfigSpec) {
	*out = *in
	if in.AdditionalConfigMaps != nil {
		in, out := &in.AdditionalConfigMaps, &out.AdditionalConfigMaps
		*out = make([]ConfigMapRef, len(*in))
		copy(*out, *in)
	}
	if in.MetricLevels != nil {
		in, out := &in.MetricLevels, &out.MetricLevels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Staleness != nil {
		in, out := &in.Staleness, &out.Staleness
		*out = new(v1.Duration)
		**out = **in
	}
	if in.SampleRate != nil {
		in, out := &in.SampleRate, &out.SampleRate
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxTerminated != nil {
		in, out := &in.MaxTerminated, &out.MaxTerminated
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerMonitorInternalKeplerConfigSpec.
func (in *PowerMonitorInternalKeplerConfigSpec) DeepCopy() *PowerMonitorInternalKeplerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(PowerMonitorInternalKeplerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerMonitorInternalKeplerDeploymentSpec) DeepCopyInto(out *PowerMonitorInternalKeplerDeploymentSpec) {
	*out = *in
	in.PowerMonitorKeplerDeploymentSpec.DeepCopyInto(&out.PowerMonitorKeplerDeploymentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerMonitorInternalKeplerDeploymentSpec.
func (in *PowerMonitorInternalKeplerDeploymentSpec) DeepCopy() *PowerMonitorInternalKeplerDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(PowerMonitorInternalKeplerDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerMonitorInternalKeplerSpec) DeepCopyInto(out *PowerMonitorInternalKeplerSpec) {
	*out = *in
	in.Deployment.DeepCopyInto(&out.Deployment)
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerMonitorInternalKeplerSpec.
func (in *PowerMonitorInternalKeplerSpec) DeepCopy() *PowerMonitorInternalKeplerSpec {
	if in == nil {
		return nil
	}
	out := new(PowerMonitorInternalKeplerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerMonitorInternalKeplerStatus) DeepCopyInto(out *PowerMonitorInternalKeplerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerMonitorInternalKeplerStatus.
func (in *PowerMonitorInternalKeplerStatus) DeepCopy() *PowerMonitorInternalKeplerStatus {
	if in == nil {
		return nil
	}
	out := new(PowerMonitorInternalKeplerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerMonitorInternalList) DeepCopyInto(out *PowerMonitorInternalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PowerMonitorInternal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerMonitorInternalList.
func (in *PowerMonitorInternalList) DeepCopy() *PowerMonitorInternalList {
	if in == nil {
		return nil
	}
	out := new(PowerMonitorInternalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PowerMonitorInternalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerMonitorInternalOpenShiftSpec) DeepCopyInto(out *PowerMonitorInternalOpenShiftSpec) {
	*out = *in
	out.Dashboard = in.Dashboard
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerMonitorInternalOpenShiftSpec.
func (in *PowerMonitorInternalOpenShiftSpec) DeepCopy() *PowerMonitorInternalOpenShiftSpec {
	if in == nil {
		return nil
	}
	out := new(PowerMonitorInternalOpenShiftSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerMonitorInternalSpec) DeepCopyInto(out *PowerMonitorInternalSpec) {
	*out = *in
	in.Kepler.DeepCopyInto(&out.Kepler)
	out.OpenShift = in.OpenShift
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerMonitorInternalSpec.
func (in *PowerMonitorInternalSpec) DeepCopy() *PowerMonitorInternalSpec {
	if in == nil {
		return nil
	}
	out := new(PowerMonitorInternalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerMonitorInternalStatus) DeepCopyInto(out *PowerMonitorInternalStatus) {
	*out = *in
	out.Kepler = in.Kepler
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerMonitorInternalStatus.
func (in *PowerMonitorInternalStatus) DeepCopy() *PowerMonitorInternalStatus {
	if in == nil {
		return nil
	}
	out := new(PowerMonitorInternalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerMonitorKeplerConfigSpec) DeepCopyInto(out *PowerMonitorKeplerConfigSpec) {
	*out = *in
	if in.AdditionalConfigMaps != nil {
		in, out := &in.AdditionalConfigMaps, &out.AdditionalConfigMaps
		*out = make([]ConfigMapRef, len(*in))
		copy(*out, *in)
	}
	if in.MetricLevels != nil {
		in, out := &in.MetricLevels, &out.MetricLevels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Staleness != nil {
		in, out := &in.Staleness, &out.Staleness
		*out = new(v1.Duration)
		**out = **in
	}
	if in.SampleRate != nil {
		in, out := &in.SampleRate, &out.SampleRate
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxTerminated != nil {
		in, out := &in.MaxTerminated, &out.MaxTerminated
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerMonitorKeplerConfigSpec.
func (in *PowerMonitorKeplerConfigSpec) DeepCopy() *PowerMonitorKeplerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(PowerMonitorKeplerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerMonitorKeplerDeploymentSecuritySpec) DeepCopyInto(out *PowerMonitorKeplerDeploymentSecuritySpec) {
	*out = *in
	if in.AllowedSANames != nil {
		in, out := &in.AllowedSANames, &out.AllowedSANames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerMonitorKeplerDeploymentSecuritySpec.
func (in *PowerMonitorKeplerDeploymentSecuritySpec) DeepCopy() *PowerMonitorKeplerDeploymentSecuritySpec {
	if in == nil {
		return nil
	}
	out := new(PowerMonitorKeplerDeploymentSecuritySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerMonitorKeplerDeploymentSpec) DeepCopyInto(out *PowerMonitorKeplerDeploymentSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Security.DeepCopyInto(&out.Security)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerMonitorKeplerDeploymentSpec.
func (in *PowerMonitorKeplerDeploymentSpec) DeepCopy() *PowerMonitorKeplerDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(PowerMonitorKeplerDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerMonitorKeplerSpec) DeepCopyInto(out *PowerMonitorKeplerSpec) {
	*out = *in
	in.Deployment.DeepCopyInto(&out.Deployment)
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerMonitorKeplerSpec.
func (in *PowerMonitorKeplerSpec) DeepCopy() *PowerMonitorKeplerSpec {
	if in == nil {
		return nil
	}
	out := new(PowerMonitorKeplerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerMonitorKeplerStatus) DeepCopyInto(out *PowerMonitorKeplerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerMonitorKeplerStatus.
func (in *PowerMonitorKeplerStatus) DeepCopy() *PowerMonitorKeplerStatus {
	if in == nil {
		return nil
	}
	out := new(PowerMonitorKeplerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerMonitorList) DeepCopyInto(out *PowerMonitorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PowerMonitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerMonitorList.
func (in *PowerMonitorList) DeepCopy() *PowerMonitorList {
	if in == nil {
		return nil
	}
	out := new(PowerMonitorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PowerMonitorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerMonitorSpec) DeepCopyInto(out *PowerMonitorSpec) {
	*out = *in
	in.Kepler.DeepCopyInto(&out.Kepler)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerMonitorSpec.
func (in *PowerMonitorSpec) DeepCopy() *PowerMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(PowerMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerMonitorStatus) DeepCopyInto(out *PowerMonitorStatus) {
	*out = *in
	out.Kepler = in.Kepler
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerMonitorStatus.
func (in *PowerMonitorStatus) DeepCopy() *PowerMonitorStatus {
	if in == nil {
		return nil
	}
	out := new(PowerMonitorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityConfig) DeepCopyInto(out *SecurityConfig) {
	*out = *in
	if in.AllowedSANames != nil {
		in, out := &in.AllowedSANames, &out.AllowedSANames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityConfig.
func (in *SecurityConfig) DeepCopy() *SecurityConfig {
	if in == nil {
		return nil
	}
	out := new(SecurityConfig)
	in.DeepCopyInto(out)
	return out
}
