resources:
- ../../base

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: controller
      namespace: system
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/0
        value: --deployment-namespace=power-monitor
