{
 "title": "Power Monitoring / Overview",
 "description": "Power Monitoring overview",
 "tags": [ "kepler-mixin" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU architecture / Monitored Nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by (cpu_architecture)(kepler_node_info) "
    }
   ]
  },
  {
   "title": "Total Energy Consumption - Last 24 hours",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(sum by (container_namespace) (\n  (increase(kepler_container_joules_total{container_namespace=~\".*\"}[1h])\n    * 0.000000277777777777778\n  ) *\n  (count_over_time(kepler_container_joules_total{container_namespace=~\".*\"}[24h])/\n    count_over_time(kepler_container_joules_total{container_namespace=~\".*\"}[1h])\n  )\n))"
    }
   ]
  },
  {
   "title": "Total Power Consumption for Top 10 Namespaces (kWh per day) - Last 24 hours",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "topk(10, sum by (container_namespace) (\n  (increase(kepler_container_package_joules_total{container_namespace=~\".*\"}[1h])\n    *0.000000277777777777778\n  ) *\n  (count_over_time(kepler_container_package_joules_total{container_namespace=~\".*\"}[24h])/\n    count_over_time(kepler_container_package_joules_total{container_namespace=~\".*\"}[1h])\n  )\n)\n+\nsum by (container_namespace) (\n  (increase(kepler_container_dram_joules_total{container_namespace=~\".*\"}[1h])\n    *0.000000277777777777778\n  ) *\n  (count_over_time(kepler_container_dram_joules_total{container_namespace=~\".*\"}[24h])/\n    count_over_time(kepler_container_dram_joules_total{container_namespace=~\".*\"}[1h])\n  )\n))",
     "legendFormat": "{{container_namespace}}"
    }
   ]
  }
 ]
}