{
 "title": "Power Monitoring / Namespace",
 "description": "Power Monitoring / Namespace",
 "tags": [ "kepler-mixin" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kepler_container_package_joules_total, container_namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}, pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pod/Process (PKG) Power Consumption (W)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "W" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name, container_namespace) (irate(kepler_container_package_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[1m]))",
     "legendFormat": "{{pod_name}} / {{container_namespace}} / PKG"
    }
   ]
  },
  {
   "title": "Pod/Process (DRAM) Power Consumption (W)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "W" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name, container_namespace) (irate(kepler_container_dram_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[1m]))",
     "legendFormat": "{{pod_name}} / {{container_namespace}} / DRAM"
    }
   ]
  },
  {
   "title": "Pod/Process (GPU) Power Consumption (W)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "W" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name, container_namespace) (irate(kepler_container_gpu_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[1m]))",
     "legendFormat": "{{pod_name}} / {{container_namespace}} / GPU"
    }
   ]
  },
  {
   "title": "Pod/Process (OTHER) Power Consumption (W)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name, container_namespace) (irate(kepler_container_other_host_components_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[1m]))",
     "legendFormat": "{{pod_name}} / {{container_namespace}} / OTHER"
    }
   ]
  },
  {
   "title": "Total Power Consumption (W) in Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "W" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(irate(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[1m])))",
     "legendFormat": "PKG"
    },
    {
     "expr": "topk(10, sum(irate(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[1m])))",
     "legendFormat": "DRAM"
    },
    {
     "expr": "topk(10,sum(irate(kepler_container_other_host_components_joules_total{container_namespace=~\"$namespace\"}[1m])))",
     "legendFormat": "OTHER"
    },
    {
     "expr": "topk(10, sum(irate(kepler_container_gpu_joules_total{container_namespace=~\"$namespace\"}[1m])))",
     "legendFormat": "GPU"
    }
   ]
  },
  {
   "title": "Total Power Consumption (kWh per day) in Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "kWh" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(\n  (increase(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[1h])\n    *0.000000277777777777778\n  ) *\n  (count_over_time(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[24h])/\n    count_over_time(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[1h])\n  )\n))",
     "legendFormat": "PKG (CORE+UNCORE)"
    },
    {
     "expr": "topk(10, sum(\n  (increase(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[1h])\n    *0.000000277777777777778\n  ) *\n  (count_over_time(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[24h])/\n    count_over_time(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[1h])\n  )\n))",
     "legendFormat": "DRAM"
    },
    {
     "expr": "topk(10, sum(\n  (increase(\n    kepler_container_other_host_components_joules_total{container_namespace=~\"$namespace\"}[1h])\n    *0.000000277777777777778\n  ) *\n  (count_over_time(\n    kepler_container_other_host_components_joules_total{container_namespace=~\"$namespace\"}[24h])/\n    count_over_time(\n      kepler_container_other_host_components_joules_total{container_namespace=~\"$namespace\"}[1h])\n  )\n))",
     "legendFormat": "OTHER"
    },
    {
     "expr": "topk(10, sum(\n  (increase(kepler_container_gpu_joules_total{container_namespace=~\"$namespace\"}[1h])\n    *0.000000277777777777778\n  ) *\n  (count_over_time(kepler_container_gpu_joules_total{container_namespace=~\"$namespace\"}[24h])/\n    count_over_time(kepler_container_gpu_joules_total{container_namespace=~\"$namespace\"}[1h])\n  )\n))",
     "legendFormat": " GPU"
    }
   ]
  }
 ]
}