{
 "title": "Kepler Exporter Dashboard",
 "description": "Dashboard for Kepler Exporter",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kepler_container_package_joules_total, container_namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}, pod_name)"
    }
   },
   { "name": "coal", "label": "Coal Coeff", "query": "2.23" },
   { "name": "natural_gas", "label": "Natural Gas Coeff", "query": "0.91" },
   { "name": "petroleum", "label": "Petroleum Coeff", "query": "2.13" },
   { "name": "watt_per_second_to_kWh", "query": "0.000000277777777777778" }
  ]
 },
 "panels": [
  { "title": "Carbon Emissions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Carbon Footprint (pounds per kWh per day) in Namespace: $namespace or Top 10 Namespaces if ALL Namespaces is selected (PKG+DRAM)",
   "type": "gauge",
   "description": "Using CO2 emissions  by power generation type as reported by US Energy Information Administration https://www.eia.gov/tools/faqs/faq.php?id=74&t=11",
   "gridPos": { "h": 6, "w": 19, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum(\n    (increase(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[1h])\n     *$watt_per_second_to_kWh\n    ) *\n   (count_over_time(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[24h])/\n      count_over_time(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[1h])\n   )\n  ) * $coal\n)\n+\n(sum(\n    (increase(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[1h])\n     *$watt_per_second_to_kWh\n    ) *\n   (count_over_time(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[24h])/\n      count_over_time(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[1h])\n   )\n  ) * $coal\n)",
     "legendFormat": "CO2 Coal"
    },
    {
     "expr": "topk(10,sum(\n    (increase(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[1h])\n     *$watt_per_second_to_kWh\n    ) *\n   (count_over_time(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[24h])/\n      count_over_time(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[1h])\n   )\n  ) * $petroleum\n)\n+\n(sum(\n    (increase(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[1h])\n     *$watt_per_second_to_kWh\n    ) *\n   (count_over_time(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[24h])/\n      count_over_time(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[1h])\n   )\n  ) * $petroleum\n)",
     "legendFormat": "CO2 Petroleum"
    },
    {
     "expr": "topk(10,sum(\n    (increase(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[1h])\n     *$watt_per_second_to_kWh\n    ) *\n   (count_over_time(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[24h])/\n      count_over_time(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[1h])\n   )\n  ) * $natural_gas\n)\n+\n(sum(\n    (increase(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[1h])\n     *$watt_per_second_to_kWh\n    ) *\n   (count_over_time(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[24h])/\n      count_over_time(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[1h])\n   )\n  ) * $natural_gas\n)",
     "legendFormat": "CO2 Natural Gas"
    }
   ]
  },
  { "title": "Power Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Pod/Process Power Consumption (W) in Namespace: $namespace",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (pod_name, container_namespace) (irate(kepler_container_package_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[1m]))",
     "legendFormat": "{{pod_name}} / {{container_namespace}} / PKG"
    },
    {
     "expr": "sum by (pod_name, container_namespace) (irate(kepler_container_dram_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[1m]))",
     "legendFormat": "{{pod_name}} / {{container_namespace}} / DRAM"
    },
    {
     "expr": "sum by (pod_name, container_namespace) (irate(kepler_container_other_host_components_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[1m]))",
     "legendFormat": "{{pod_name}} / {{container_namespace}} / OTHER"
    },
    {
     "expr": "sum by (pod_name, container_namespace) (irate(kepler_container_gpu_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[1m]))",
     "legendFormat": "{{pod_name}} / {{container_namespace}} / GPU"
    }
   ]
  },
  {
   "title": "Power Consumption (W) of Top10 processes in Namespace: $namespace or Top 10 Namespace if ALL namespaces is selected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "topk(10, sum(irate(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[1m])))",
     "legendFormat": "PKG"
    },
    {
     "expr": "topk(10, sum(irate(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[1m])))",
     "legendFormat": "DRAM"
    },
    {
     "expr": "topk(10,sum(irate(kepler_container_other_host_components_joules_total{container_namespace=~\"$namespace\"}[1m])))",
     "legendFormat": "OTHER"
    },
    {
     "expr": "topk(10, sum(irate(kepler_container_gpu_joules_total{container_namespace=~\"$namespace\"}[1m])))",
     "legendFormat": " GPU"
    }
   ]
  },
  {
   "title": "Total Power Consumption (kWh per day) of Top10 processes in Namespace: $namespace or Top10 Namesapces if All Namespaces selected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "topk(10, sum(\n  (increase(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[1h])\n    *$watt_per_second_to_kWh\n  ) *\n  (count_over_time(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[24h])/\n    count_over_time(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[1h])\n  )\n))",
     "legendFormat": "PKG (CORE+UNCORE)"
    },
    {
     "expr": "topk(10, sum(\n  (increase(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[1h])\n    *$watt_per_second_to_kWh\n  ) *\n  (count_over_time(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[24h])/\n    count_over_time(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[1h])\n  )\n))",
     "legendFormat": "DRAM"
    },
    {
     "expr": "topk(10, sum(\n  (increase(\n    kepler_container_other_host_components_joules_total{container_namespace=~\"$namespace\"}[1h])\n    *$watt_per_second_to_kWh\n  ) *\n  (count_over_time(\n    kepler_container_other_host_components_joules_total{container_namespace=~\"$namespace\"}[24h])/\n    count_over_time(\n      kepler_container_other_host_components_joules_total{container_namespace=~\"$namespace\"}[1h])\n  )\n))",
     "legendFormat": "OTHER"
    },
    {
     "expr": "topk(10, sum(\n  (increase(kepler_container_gpu_joules_total{container_namespace=~\"$namespace\"}[1h])\n    *$watt_per_second_to_kWh\n  ) *\n  (count_over_time(kepler_container_gpu_joules_total{container_namespace=~\"$namespace\"}[24h])/\n    count_over_time(kepler_container_gpu_joules_total{container_namespace=~\"$namespace\"}[1h])\n  )\n))",
     "legendFormat": " GPU"
    }
   ]
  },
  {
   "title": "Total Power Consumption (PKG+DRAM) for Namespace: $namespace or Top 10 Namespaces if ALL Namespaces is selected (kWh per day)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (container_namespace) (\n  (increase(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[1h])\n    *$watt_per_second_to_kWh\n  ) *\n  (count_over_time(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[24h])/\n    count_over_time(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[1h])\n  )\n)\n+\nsum by (container_namespace) (\n  (increase(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[1h])\n    *$watt_per_second_to_kWh\n  ) *\n  (count_over_time(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[24h])/\n    count_over_time(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[1h])\n  )\n))",
     "legendFormat": "{{container_namespace}}"
    }
   ]
  }
 ]
}