name: Compute Version
description: computes version of the operator
outputs:
  version:
    description: operator version
    value: ${{ steps.version.outputs.version }}
runs:
  using: composite
  steps:
    - name: Generate Version
      id: version
      shell: bash
      run: |
        version="$(cat VERSION)-$(date +%Y%m%d%H%M%S)"
        echo VERSION=$version
        echo "version=$version" >> $GITHUB_OUTPUT
