name: bundle checker

on:
  pull_request:

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@main
        with:
          go-version-file: go.mod

      - name: bundle
        run: |
          make generate manifests bundle
          git diff --ignore-matching-lines='createdAt:' --exit-code
