name: Publish Images

on:
  push:
    branches: [ v1alpha1 ]

jobs:
  publish:
      name: Publish operator container images
      runs-on: ubuntu-latest
      steps:
        - name: Checkout source
          uses: actions/checkout@v3

        - uses: actions/setup-go@main
          with:
            go-version-file: go.mod
            cache: true

        - uses: ./.github/compute-version
          id: version

        - name: additional tags
          id: additional_tags
          shell: bash
          run: |
            echo "result=$(git rev-parse --short HEAD),v1alpha1" >> $GITHUB_OUTPUT

        - name: build and publish images to external registry
          uses: ./.github/publish-images
          with:
            image_registry: ${{ vars.IMG_BASE }}
            registry_login: ${{ secrets.BOT_NAME }}
            registry_token: ${{ secrets.BOT_TOKEN }}
            version: ${{ steps.version.outputs.version }}
            additional_tags: ${{ steps.additional_tags.outputs.result }}
