name: Test and Upload Coverage

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        description: Codecov token
        required: true

jobs:
  test:
    runs-on: ubuntu-latest-8-cores
    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: false

      - name: Run tests and generate coverage
        shell: bash
        run: make test

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v5
        with:
          name: coverage-report
          path: cover.out # The file name of the coverage report should be same as what make target uses

  coverage-upload:
    needs: test
    runs-on: ubuntu-latest-8-cores
    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Download coverage report artifact
        uses: actions/download-artifact@v6
        with:
          name: coverage-report

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.5.1
        with:
          fail_ci_if_error: true
          files: ./cover.out
          token: ${{ secrets.CODECOV_TOKEN }}
